[profile.default]
solc_version = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "@pythnetwork/pyth-sdk-solidity/=lib/pyth-sdk-solidity/"
]

via_ir = true
optimizer = true
optimizer_runs = 200

[profile.default.rpc_endpoints]
espace = "${ESPACE_RPC}"
